import type { DataDropdown } from '@abqm-ds/react';

export const estados: DataDropdown[] = [
  { value: 'AC', label: 'Acre', id: '0' },
  { value: 'AL', label: 'Alagoas', id: '1' },
  { value: 'AP', label: 'Amapá', id: '2' },
  { value: 'AM', label: 'Amazonas', id: '3' },
  { value: 'BA', label: 'Bahia', id: '4' },
  { value: 'CE', label: 'Ceará', id: '5' },
  { value: 'DF', label: 'Distrito Federal', id: '6' },
  { value: 'ES', label: 'Espírito Santo', id: '7' },
  { value: 'GO', label: 'Goiás', id: '8' },
  { value: 'MA', label: 'Maranhão', id: '9' },
  { value: 'MT', label: 'Mato Grosso', id: '10' },
  { value: 'MS', label: 'Mato Grosso do Sul', id: '11' },
  { value: 'MG', label: 'Minas Gerais', id: '12' },
  { value: 'PA', label: 'Pará', id: '13' },
  { value: 'PB', label: 'Paraíba', id: '14' },
  { value: 'PR', label: 'Paraná', id: '15' },
  { value: 'PE', label: 'Pernambuco', id: '16' },
  { value: 'PI', label: 'Piauí', id: '17' },
  { value: 'RJ', label: 'Rio de Janeiro', id: '18' },
  { value: 'RN', label: 'Rio Grande do Norte', id: '19' },
  { value: 'RS', label: 'Rio Grande do Sul', id: '20' },
  { value: 'RO', label: 'Rondônia', id: '21' },
  { value: 'RR', label: 'Roraima', id: '22' },
  { value: 'SC', label: 'Santa Catarina', id: '23' },
  { value: 'SP', label: 'São Paulo', id: '24' },
  { value: 'SE', label: 'Sergipe', id: '25' },
  { value: 'TO', label: 'Tocantins', id: '26' },
];
